### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by saadinoyucu** [lucko515/speech-recognition-neural-network#6]
jupyter notebook, getting error on kernel connection.

`File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[I 10:22:07.220 NotebookApp] KernelRestarter: restarting kernel (4/5), keep random ports
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/ubuntu/anaconda3/envs/aind-vui/lib/python3.5/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[W 10:22:10.245 NotebookApp] KernelRestarter: restart failed
[W 10:22:10.246 NotebookApp] Kernel 7008793e-d30b-4056-b45f-854269c1b400 died, removing from map.
[W 10:22:41.367 NotebookApp] Timeout waiting for kernel_info reply from 8c712274-6346-4a59-acdb-b48b57744973
**[E 10:22:41.372 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 8c712274-6346-4a59-acdb-b48b57744973)
[W 10:22:41.391 NotebookApp] 404 GET /api/kernels/7008793e-d30b-4056-b45f-854269c1b400/channels?session_id=a0a7cb01c3c644a3a135bedafc1996ea (127.0.0.1): Kernel does not exist: 7008793e-d30b-4056-b45f-854269c1b400
[W 10:22:41.424 NotebookApp] 404 GET /api/kernels/7008793e-d30b-4056-b45f-854269c1b400/channels?session_id=a0a7cb01c3c644a3a135bedafc1996ea (127.0.0.1) 39.32ms referer=None
[W 10:22:42.438 NotebookApp] Replacing stale connection: 7008793e-d30b-4056-b45f-854269c1b400:a0a7cb01c3c644a3a135bedafc1996ea
[3126:3126:0513/102307.294600:ERROR:gcm_channel_status_request.cc(151)] GCM channel request failed.
[3126:3126:0513/102335.242424:ERROR:gcm_channel_status_request.cc(151)] GCM channel request failed.
[I 10:23:40.856 NotebookApp] Saving file at /vui_notebook.ipynb
[3126:3126:0513/102428.160312:ERROR:gcm_channel_status_request.cc(151)] GCM channel request failed.
`**

**Comment by saadinoyucu** [comment]
for windows

RuntimeError: This event loop is already running
[W 11:28:36.100 NotebookApp] KernelRestarter: restart failed
[W 11:28:36.100 NotebookApp] Kernel 638e8712-f93a-4a31-a0d0-46ecd2a13174 died, removing from map.
[W 11:29:21.094 NotebookApp] Timeout waiting for kernel_info reply from 638e8712-f93a-4a31-a0d0-46ecd2a13174
[E 11:29:21.096 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 638e8712-f93a-4a31-a0d0-46ecd2a13174)
